Repository dkaiamit/DataAnalytics, pull requests merged in 2022-10, with the labels that each got.

#4 Create Data.py
  Python/Data.py
Labels: enhancement

#6 Update and rename Data.py to utils.py
  Python/utils.py
Labels: enhancement

#8 Create sqlutils
  SQL/sqlutils
Labels: documentation

#9 Update utils.py
  Python/utils.py
Labels: enhancement

#10 Update utils.py
  Python/utils.py
Labels: enhancement

#12 Update utils.py
  Python/utils.py
Labels: enhancement, help wanted

#16 Update sqlutils
  SQL/sqlutils
Labels: enhancement

#17 Create Documentation
  Documentation
Labels: documentation

#19 Update utils.py
  Python/utils.py
Labels: enhancement
